# Generated by Django 4.0.5 on 2022-06-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('economy', models.FloatField()),
                ('economy_plus', models.FloatField()),
                ('business', models.FloatField()),
                ('first_class', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_routes', to='flights.city')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('arrival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='flights.flightroute')),
                ('departure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flights.flightroute')),
                ('price', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='flights.flightprice')),
            ],
        ),
    ]
